pattern: ^(main|develop){1}$|^(feat|fix)\-.+$
errorMsg: |
    Branch naming convention error.
    Your branch doesn't follow the naming conventions, please use the command below to rename it:
     
    git branch -m <old_name> <new_name>
